version: '3.8'

services:
  # 1. Dịch vụ Cơ sở dữ liệu MySQL
  db:
    image: mysql:8.0
    container_name: hotel_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_room_booking
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Tự động nạp cấu hình và dữ liệu ban đầu khi MySQL chạy lần đầu
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    networks:
      - hotel_network

  # 2. Dịch vụ Ứng dụng Python
  app:
    build: .
    container_name: hotel_python_app
    restart: always
    stdin_open: true # Cho phép tương tác qua Terminal (nếu dùng ứng dụng console)
    tty: true        # Bật giao diện console cho Python
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: hotel_room_booking
      DB_PORT: 3306
    volumes:
      - .:/app       # Synchronize code từ máy thật vào container để sửa code không cần build lại
    depends_on:
      - db
    networks:
      - hotel_network

volumes:
  db_data:

networks:
  hotel_network:
    driver: bridge