services:
  db:
    image: mysql:8.0
    container_name: hotel_mysql_db
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_room_booking
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    networks:
      - hotel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: hotel_python_app
    restart: always
    ports:
      - "6080:6080"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: hotel_room_booking
      DB_PORT: 3306
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hotel_network

volumes:
  db_data:

networks:
  hotel_network:
    driver: bridge